// Code generated by goctl. DO NOT EDIT.
// Source: chickenroad2_srv.proto

package server

import (
	"context"

	"cocogame-max/chickenroad2_srv/internal/logic"
	"cocogame-max/chickenroad2_srv/internal/svc"
	"cocogame-max/chickenroad2_srv/pb_chickenroad2"
)

type ChickenRoad2SrvServer struct {
	svcCtx *svc.ServiceContext
	pb_chickenroad2.UnimplementedChickenRoad2SrvServer
}

func NewChickenRoad2SrvServer(svcCtx *svc.ServiceContext) *ChickenRoad2SrvServer {
	return &ChickenRoad2SrvServer{
		svcCtx: svcCtx,
	}
}

func (s *ChickenRoad2SrvServer) Auth(ctx context.Context, in *pb_chickenroad2.ChickenRoad2_Auth) (*pb_chickenroad2.ChickenRoad2_AuthResp, error) {
	l := logic.NewAuthLogic(ctx, s.svcCtx)
	return l.Auth(in)
}

func (s *ChickenRoad2SrvServer) Receive(ctx context.Context, in *pb_chickenroad2.ReceiveRequest) (*pb_chickenroad2.Empty, error) {
	l := logic.NewReceiveLogic(ctx, s.svcCtx)
	return l.Receive(in)
}
