// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.9
// source: login_srv.proto

package pb_login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gt                  int32  `protobuf:"varint,1,opt,name=Gt,proto3" json:"Gt,omitempty"`                                  // deprecaded
	GameId              int32  `protobuf:"varint,2,opt,name=GameId,proto3" json:"GameId,omitempty"`                          // 游戏id
	OperatorPlayerToken string `protobuf:"bytes,3,opt,name=OperatorPlayerToken,proto3" json:"OperatorPlayerToken,omitempty"` // 运营商用户token
	OperatorToken       string `protobuf:"bytes,4,opt,name=OperatorToken,proto3" json:"OperatorToken,omitempty"`             // 运营商token
	OperatorParam       string `protobuf:"bytes,5,opt,name=OperatorParam,proto3" json:"OperatorParam,omitempty"`             // 运营商自定义参数
	Ip                  string `protobuf:"bytes,6,opt,name=Ip,proto3" json:"Ip,omitempty"`                                   // 玩家IP
}

func (x *Req_Login) Reset() {
	*x = Req_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Login) ProtoMessage() {}

func (x *Req_Login) ProtoReflect() protoreflect.Message {
	mi := &file_login_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Login.ProtoReflect.Descriptor instead.
func (*Req_Login) Descriptor() ([]byte, []int) {
	return file_login_srv_proto_rawDescGZIP(), []int{0}
}

func (x *Req_Login) GetGt() int32 {
	if x != nil {
		return x.Gt
	}
	return 0
}

func (x *Req_Login) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Req_Login) GetOperatorPlayerToken() string {
	if x != nil {
		return x.OperatorPlayerToken
	}
	return ""
}

func (x *Req_Login) GetOperatorToken() string {
	if x != nil {
		return x.OperatorToken
	}
	return ""
}

func (x *Req_Login) GetOperatorParam() string {
	if x != nil {
		return x.OperatorParam
	}
	return ""
}

func (x *Req_Login) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Res_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *Res_Login) Reset() {
	*x = Res_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_Login) ProtoMessage() {}

func (x *Res_Login) ProtoReflect() protoreflect.Message {
	mi := &file_login_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_Login.ProtoReflect.Descriptor instead.
func (*Res_Login) Descriptor() ([]byte, []int) {
	return file_login_srv_proto_rawDescGZIP(), []int{1}
}

func (x *Res_Login) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Req_Alive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	GameId int32  `protobuf:"varint,2,opt,name=GameId,proto3" json:"GameId,omitempty"`
}

func (x *Req_Alive) Reset() {
	*x = Req_Alive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_Alive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_Alive) ProtoMessage() {}

func (x *Req_Alive) ProtoReflect() protoreflect.Message {
	mi := &file_login_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_Alive.ProtoReflect.Descriptor instead.
func (*Req_Alive) Descriptor() ([]byte, []int) {
	return file_login_srv_proto_rawDescGZIP(), []int{2}
}

func (x *Req_Alive) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Req_Alive) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type Res_Alive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime string `protobuf:"bytes,1,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
}

func (x *Res_Alive) Reset() {
	*x = Res_Alive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_Alive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_Alive) ProtoMessage() {}

func (x *Res_Alive) ProtoReflect() protoreflect.Message {
	mi := &file_login_srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_Alive.ProtoReflect.Descriptor instead.
func (*Res_Alive) Descriptor() ([]byte, []int) {
	return file_login_srv_proto_rawDescGZIP(), []int{3}
}

func (x *Res_Alive) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

var File_login_srv_proto protoreflect.FileDescriptor

var file_login_srv_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0xc1, 0x01, 0x0a, 0x09,
	0x52, 0x65, 0x71, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x47, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x47, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x13, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70, 0x22,
	0x21, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x39, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x5f, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x2b, 0x0a,
	0x09, 0x52, 0x65, 0x73, 0x5f, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x74, 0x0a, 0x08, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x53, 0x72, 0x76, 0x12, 0x33, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x13, 0x2e, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x05, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x71, 0x5f, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_login_srv_proto_rawDescOnce sync.Once
	file_login_srv_proto_rawDescData = file_login_srv_proto_rawDesc
)

func file_login_srv_proto_rawDescGZIP() []byte {
	file_login_srv_proto_rawDescOnce.Do(func() {
		file_login_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_srv_proto_rawDescData)
	})
	return file_login_srv_proto_rawDescData
}

var file_login_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_login_srv_proto_goTypes = []interface{}{
	(*Req_Login)(nil), // 0: pb_login.Req_Login
	(*Res_Login)(nil), // 1: pb_login.Res_Login
	(*Req_Alive)(nil), // 2: pb_login.Req_Alive
	(*Res_Alive)(nil), // 3: pb_login.Res_Alive
}
var file_login_srv_proto_depIdxs = []int32{
	0, // 0: pb_login.LoginSrv.Login:input_type -> pb_login.Req_Login
	2, // 1: pb_login.LoginSrv.Alive:input_type -> pb_login.Req_Alive
	1, // 2: pb_login.LoginSrv.Login:output_type -> pb_login.Res_Login
	3, // 3: pb_login.LoginSrv.Alive:output_type -> pb_login.Res_Alive
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_srv_proto_init() }
func file_login_srv_proto_init() {
	if File_login_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_login_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_Alive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_Alive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_srv_proto_goTypes,
		DependencyIndexes: file_login_srv_proto_depIdxs,
		MessageInfos:      file_login_srv_proto_msgTypes,
	}.Build()
	File_login_srv_proto = out.File
	file_login_srv_proto_rawDesc = nil
	file_login_srv_proto_goTypes = nil
	file_login_srv_proto_depIdxs = nil
}
