// Code generated by goctl. DO NOT EDIT.
// Source: playercenter_srv.proto

package playercentersrv

import (
	"context"

	"cocogame-max/chickenroad2_srv/proto/playercenter_srv/pb_playercenter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Req_Account             = pb_playercenter.Req_Account
	Req_Alive               = pb_playercenter.Req_Alive
	Req_GetRole             = pb_playercenter.Req_GetRole
	Req_GetSessionId        = pb_playercenter.Req_GetSessionId
	Req_IsExisted           = pb_playercenter.Req_IsExisted
	Req_Login               = pb_playercenter.Req_Login
	Req_SetBigBassRole      = pb_playercenter.Req_SetBigBassRole
	Req_SetDoggyRole        = pb_playercenter.Req_SetDoggyRole
	Req_SetDragonRole       = pb_playercenter.Req_SetDragonRole
	Req_SetDragonSlayerRole = pb_playercenter.Req_SetDragonSlayerRole
	Req_SetHandOfAnubisRole = pb_playercenter.Req_SetHandOfAnubisRole
	Req_SetIteroRole        = pb_playercenter.Req_SetIteroRole
	Req_SetJacksCryptRole   = pb_playercenter.Req_SetJacksCryptRole
	Req_SetJellyRole        = pb_playercenter.Req_SetJellyRole
	Req_SetJohnWildRole     = pb_playercenter.Req_SetJohnWildRole
	Req_SetMagicalMineRole  = pb_playercenter.Req_SetMagicalMineRole
	Req_SetMoneytrainRole   = pb_playercenter.Req_SetMoneytrainRole
	Req_SetRipCityRole      = pb_playercenter.Req_SetRipCityRole
	Req_SetRole             = pb_playercenter.Req_SetRole
	Req_SetWantedRole       = pb_playercenter.Req_SetWantedRole
	Req_SetWarriorWaysRole  = pb_playercenter.Req_SetWarriorWaysRole
	Res_AccountStatus       = pb_playercenter.Res_AccountStatus
	Res_Alive               = pb_playercenter.Res_Alive
	Res_GetBigBassRole      = pb_playercenter.Res_GetBigBassRole
	Res_GetDoggyRole        = pb_playercenter.Res_GetDoggyRole
	Res_GetDragonRole       = pb_playercenter.Res_GetDragonRole
	Res_GetDragonSlayerRole = pb_playercenter.Res_GetDragonSlayerRole
	Res_GetHandOfAnubisRole = pb_playercenter.Res_GetHandOfAnubisRole
	Res_GetIteroRole        = pb_playercenter.Res_GetIteroRole
	Res_GetJacksCryptRole   = pb_playercenter.Res_GetJacksCryptRole
	Res_GetJellyRole        = pb_playercenter.Res_GetJellyRole
	Res_GetJohnWildRole     = pb_playercenter.Res_GetJohnWildRole
	Res_GetMagicalMineRole  = pb_playercenter.Res_GetMagicalMineRole
	Res_GetMoneytrainRole   = pb_playercenter.Res_GetMoneytrainRole
	Res_GetOperatorRole     = pb_playercenter.Res_GetOperatorRole
	Res_GetRipCityRole      = pb_playercenter.Res_GetRipCityRole
	Res_GetRole             = pb_playercenter.Res_GetRole
	Res_GetSeed             = pb_playercenter.Res_GetSeed
	Res_GetSessionId        = pb_playercenter.Res_GetSessionId
	Res_GetWantedRole       = pb_playercenter.Res_GetWantedRole
	Res_GetWarriorWaysRole  = pb_playercenter.Res_GetWarriorWaysRole
	Res_IsExisted           = pb_playercenter.Res_IsExisted
	Res_Login               = pb_playercenter.Res_Login
	Res_SetAccount          = pb_playercenter.Res_SetAccount
	Res_SetRole             = pb_playercenter.Res_SetRole

	PlayerCenterSrv interface {
		Login(ctx context.Context, in *Req_Login, opts ...grpc.CallOption) (*Res_Login, error)
		GetSessionId(ctx context.Context, in *Req_GetSessionId, opts ...grpc.CallOption) (*Res_GetSessionId, error)
		Alive(ctx context.Context, in *Req_Alive, opts ...grpc.CallOption) (*Res_Alive, error)
		NewAccount(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error)
		Eliminate(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error)
		Ban(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error)
		Unseal(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error)
		Status(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_AccountStatus, error)
		IsExisted(ctx context.Context, in *Req_IsExisted, opts ...grpc.CallOption) (*Res_IsExisted, error)
		GetOperatorRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetOperatorRole, error)
		GetDoggyRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetDoggyRole, error)
		SetDoggyRole(ctx context.Context, in *Req_SetDoggyRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetServerSeed(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetSeed, error)
		GetMoneytrainRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetMoneytrainRole, error)
		SetMoneytrainRole(ctx context.Context, in *Req_SetMoneytrainRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetDragonSlayerRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetDragonSlayerRole, error)
		SetDragonSlayerRole(ctx context.Context, in *Req_SetDragonSlayerRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetWantedRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetWantedRole, error)
		SetWantedRole(ctx context.Context, in *Req_SetWantedRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetMagicalMineRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetMagicalMineRole, error)
		SetMagicalMineRole(ctx context.Context, in *Req_SetMagicalMineRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetJacksCryptRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetJacksCryptRole, error)
		SetJacksCryptRole(ctx context.Context, in *Req_SetJacksCryptRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetBigBassRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetBigBassRole, error)
		SetBigBassRole(ctx context.Context, in *Req_SetBigBassRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetHandOfAnubisRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetHandOfAnubisRole, error)
		SetHandOfAnubisRole(ctx context.Context, in *Req_SetHandOfAnubisRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetDragonRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetDragonRole, error)
		SetDragonRole(ctx context.Context, in *Req_SetDragonRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetJohnWildRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetJohnWildRole, error)
		SetJohnWildRole(ctx context.Context, in *Req_SetJohnWildRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetRipCityRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetRipCityRole, error)
		SetRipCityRole(ctx context.Context, in *Req_SetRipCityRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetWarriorWaysRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetWarriorWaysRole, error)
		SetWarriorWaysRole(ctx context.Context, in *Req_SetWarriorWaysRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetJellyRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetJellyRole, error)
		SetJellyRole(ctx context.Context, in *Req_SetJellyRole, opts ...grpc.CallOption) (*Res_SetRole, error)
		GetRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetRole, error)
		SetRole(ctx context.Context, in *Req_SetRole, opts ...grpc.CallOption) (*Res_SetRole, error)
	}

	defaultPlayerCenterSrv struct {
		cli zrpc.Client
	}
)

func NewPlayerCenterSrv(cli zrpc.Client) PlayerCenterSrv {
	return &defaultPlayerCenterSrv{
		cli: cli,
	}
}

func (m *defaultPlayerCenterSrv) Login(ctx context.Context, in *Req_Login, opts ...grpc.CallOption) (*Res_Login, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetSessionId(ctx context.Context, in *Req_GetSessionId, opts ...grpc.CallOption) (*Res_GetSessionId, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetSessionId(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) Alive(ctx context.Context, in *Req_Alive, opts ...grpc.CallOption) (*Res_Alive, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.Alive(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) NewAccount(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.NewAccount(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) Eliminate(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.Eliminate(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) Ban(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.Ban(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) Unseal(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_SetAccount, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.Unseal(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) Status(ctx context.Context, in *Req_Account, opts ...grpc.CallOption) (*Res_AccountStatus, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.Status(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) IsExisted(ctx context.Context, in *Req_IsExisted, opts ...grpc.CallOption) (*Res_IsExisted, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.IsExisted(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetOperatorRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetOperatorRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetOperatorRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetDoggyRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetDoggyRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetDoggyRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetDoggyRole(ctx context.Context, in *Req_SetDoggyRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetDoggyRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetServerSeed(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetSeed, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetServerSeed(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetMoneytrainRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetMoneytrainRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetMoneytrainRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetMoneytrainRole(ctx context.Context, in *Req_SetMoneytrainRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetMoneytrainRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetDragonSlayerRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetDragonSlayerRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetDragonSlayerRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetDragonSlayerRole(ctx context.Context, in *Req_SetDragonSlayerRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetDragonSlayerRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetWantedRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetWantedRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetWantedRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetWantedRole(ctx context.Context, in *Req_SetWantedRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetWantedRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetMagicalMineRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetMagicalMineRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetMagicalMineRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetMagicalMineRole(ctx context.Context, in *Req_SetMagicalMineRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetMagicalMineRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetJacksCryptRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetJacksCryptRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetJacksCryptRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetJacksCryptRole(ctx context.Context, in *Req_SetJacksCryptRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetJacksCryptRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetBigBassRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetBigBassRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetBigBassRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetBigBassRole(ctx context.Context, in *Req_SetBigBassRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetBigBassRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetHandOfAnubisRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetHandOfAnubisRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetHandOfAnubisRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetHandOfAnubisRole(ctx context.Context, in *Req_SetHandOfAnubisRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetHandOfAnubisRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetDragonRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetDragonRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetDragonRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetDragonRole(ctx context.Context, in *Req_SetDragonRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetDragonRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetJohnWildRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetJohnWildRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetJohnWildRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetJohnWildRole(ctx context.Context, in *Req_SetJohnWildRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetJohnWildRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetRipCityRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetRipCityRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetRipCityRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetRipCityRole(ctx context.Context, in *Req_SetRipCityRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetRipCityRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetWarriorWaysRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetWarriorWaysRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetWarriorWaysRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetWarriorWaysRole(ctx context.Context, in *Req_SetWarriorWaysRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetWarriorWaysRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetJellyRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetJellyRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetJellyRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetJellyRole(ctx context.Context, in *Req_SetJellyRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetJellyRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) GetRole(ctx context.Context, in *Req_GetRole, opts ...grpc.CallOption) (*Res_GetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultPlayerCenterSrv) SetRole(ctx context.Context, in *Req_SetRole, opts ...grpc.CallOption) (*Res_SetRole, error) {
	client := pb_playercenter.NewPlayerCenterSrvClient(m.cli.Conn())
	return client.SetRole(ctx, in, opts...)
}
