// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.9
// source: order_srv.proto

package pb_order

import (
	_ "cocogame-max/chickenroad2_srv/proto/pb_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComPager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PagePage int64  `protobuf:"varint,1,opt,name=PagePage,proto3" json:"PagePage,omitempty"`
	PageRow  int64  `protobuf:"varint,2,opt,name=PageRow,proto3" json:"PageRow,omitempty"`
	PageStat string `protobuf:"bytes,3,opt,name=PageStat,proto3" json:"PageStat,omitempty"`
}

func (x *ComPager) Reset() {
	*x = ComPager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComPager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComPager) ProtoMessage() {}

func (x *ComPager) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComPager.ProtoReflect.Descriptor instead.
func (*ComPager) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{0}
}

func (x *ComPager) GetPagePage() int64 {
	if x != nil {
		return x.PagePage
	}
	return 0
}

func (x *ComPager) GetPageRow() int64 {
	if x != nil {
		return x.PageRow
	}
	return 0
}

func (x *ComPager) GetPageStat() string {
	if x != nil {
		return x.PageStat
	}
	return ""
}

type Req_GetHisotry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token         string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`                 // 玩家token
	OperatorToken string `protobuf:"bytes,2,opt,name=OperatorToken,proto3" json:"OperatorToken,omitempty"` // 运营商token
	GameCode      int32  `protobuf:"varint,3,opt,name=GameCode,proto3" json:"GameCode,omitempty"`
	StartTime     int64  `protobuf:"varint,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       int64  `protobuf:"varint,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	PagePage      int64  `protobuf:"varint,6,opt,name=PagePage,proto3" json:"PagePage,omitempty"`
	PageRow       int64  `protobuf:"varint,7,opt,name=PageRow,proto3" json:"PageRow,omitempty"`
}

func (x *Req_GetHisotry) Reset() {
	*x = Req_GetHisotry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_GetHisotry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_GetHisotry) ProtoMessage() {}

func (x *Req_GetHisotry) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_GetHisotry.ProtoReflect.Descriptor instead.
func (*Req_GetHisotry) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{1}
}

func (x *Req_GetHisotry) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Req_GetHisotry) GetOperatorToken() string {
	if x != nil {
		return x.OperatorToken
	}
	return ""
}

func (x *Req_GetHisotry) GetGameCode() int32 {
	if x != nil {
		return x.GameCode
	}
	return 0
}

func (x *Req_GetHisotry) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Req_GetHisotry) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Req_GetHisotry) GetPagePage() int64 {
	if x != nil {
		return x.PagePage
	}
	return 0
}

func (x *Req_GetHisotry) GetPageRow() int64 {
	if x != nil {
		return x.PageRow
	}
	return 0
}

type GenerateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeOrderNo int64 `protobuf:"varint,1,opt,name=TradeOrderNo,proto3" json:"TradeOrderNo,omitempty"`
}

func (x *GenerateResult) Reset() {
	*x = GenerateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResult) ProtoMessage() {}

func (x *GenerateResult) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResult.ProtoReflect.Descriptor instead.
func (*GenerateResult) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateResult) GetTradeOrderNo() int64 {
	if x != nil {
		return x.TradeOrderNo
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{3}
}

type Req_OrderNo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthToken string `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
}

func (x *Req_OrderNo) Reset() {
	*x = Req_OrderNo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_OrderNo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_OrderNo) ProtoMessage() {}

func (x *Req_OrderNo) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_OrderNo.ProtoReflect.Descriptor instead.
func (*Req_OrderNo) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{4}
}

func (x *Req_OrderNo) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type Res_OrderNo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo int64 `protobuf:"varint,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
}

func (x *Res_OrderNo) Reset() {
	*x = Res_OrderNo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_OrderNo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_OrderNo) ProtoMessage() {}

func (x *Res_OrderNo) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_OrderNo.ProtoReflect.Descriptor instead.
func (*Res_OrderNo) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{5}
}

func (x *Res_OrderNo) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

type OrderHistoryItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId      string     `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	ParentId    int64      `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	SubId       int64      `protobuf:"varint,3,opt,name=SubId,proto3" json:"SubId,omitempty"`
	SurplusCoin float64    `protobuf:"fixed64,4,opt,name=SurplusCoin,proto3" json:"SurplusCoin,omitempty"`
	BetLevel    float64    `protobuf:"fixed64,5,opt,name=BetLevel,proto3" json:"BetLevel,omitempty"`
	Bet         float64    `protobuf:"fixed64,6,opt,name=Bet,proto3" json:"Bet,omitempty"`
	Score       float64    `protobuf:"fixed64,7,opt,name=Score,proto3" json:"Score,omitempty"`
	Status      int64      `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	ReceiptId   string     `protobuf:"bytes,9,opt,name=ReceiptId,proto3" json:"ReceiptId,omitempty"`
	CreateTime  int64      `protobuf:"varint,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Role        *anypb.Any `protobuf:"bytes,11,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *OrderHistoryItem) Reset() {
	*x = OrderHistoryItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryItem) ProtoMessage() {}

func (x *OrderHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryItem.ProtoReflect.Descriptor instead.
func (*OrderHistoryItem) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{6}
}

func (x *OrderHistoryItem) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *OrderHistoryItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *OrderHistoryItem) GetSubId() int64 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *OrderHistoryItem) GetSurplusCoin() float64 {
	if x != nil {
		return x.SurplusCoin
	}
	return 0
}

func (x *OrderHistoryItem) GetBetLevel() float64 {
	if x != nil {
		return x.BetLevel
	}
	return 0
}

func (x *OrderHistoryItem) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *OrderHistoryItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OrderHistoryItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderHistoryItem) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *OrderHistoryItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OrderHistoryItem) GetRole() *anypb.Any {
	if x != nil {
		return x.Role
	}
	return nil
}

type Res_HistoryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoryItem []*OrderHistoryItem `protobuf:"bytes,1,rep,name=HistoryItem,proto3" json:"HistoryItem,omitempty"`
	ComPager    *ComPager           `protobuf:"bytes,2,opt,name=ComPager,proto3" json:"ComPager,omitempty"`
}

func (x *Res_HistoryList) Reset() {
	*x = Res_HistoryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_HistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_HistoryList) ProtoMessage() {}

func (x *Res_HistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_HistoryList.ProtoReflect.Descriptor instead.
func (*Res_HistoryList) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{7}
}

func (x *Res_HistoryList) GetHistoryItem() []*OrderHistoryItem {
	if x != nil {
		return x.HistoryItem
	}
	return nil
}

func (x *Res_HistoryList) GetComPager() *ComPager {
	if x != nil {
		return x.ComPager
	}
	return nil
}

type Req_RecommendRtp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId        int32  `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	RoleId        string `protobuf:"bytes,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	OperatorToken string `protobuf:"bytes,3,opt,name=operatorToken,proto3" json:"operatorToken,omitempty"`
}

func (x *Req_RecommendRtp) Reset() {
	*x = Req_RecommendRtp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_RecommendRtp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_RecommendRtp) ProtoMessage() {}

func (x *Req_RecommendRtp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_RecommendRtp.ProtoReflect.Descriptor instead.
func (*Req_RecommendRtp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{8}
}

func (x *Req_RecommendRtp) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Req_RecommendRtp) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Req_RecommendRtp) GetOperatorToken() string {
	if x != nil {
		return x.OperatorToken
	}
	return ""
}

type Res_RecommendRtp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RTP int32 `protobuf:"varint,1,opt,name=RTP,proto3" json:"RTP,omitempty"`
}

func (x *Res_RecommendRtp) Reset() {
	*x = Res_RecommendRtp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_RecommendRtp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_RecommendRtp) ProtoMessage() {}

func (x *Res_RecommendRtp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_RecommendRtp.ProtoReflect.Descriptor instead.
func (*Res_RecommendRtp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{9}
}

func (x *Res_RecommendRtp) GetRTP() int32 {
	if x != nil {
		return x.RTP
	}
	return 0
}

type Req_RecommendRiskConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId        int32  `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	RoleId        string `protobuf:"bytes,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	OperatorToken string `protobuf:"bytes,3,opt,name=operatorToken,proto3" json:"operatorToken,omitempty"`
	UsingRTP      int32  `protobuf:"varint,4,opt,name=UsingRTP,proto3" json:"UsingRTP,omitempty"`
}

func (x *Req_RecommendRiskConfig) Reset() {
	*x = Req_RecommendRiskConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_RecommendRiskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_RecommendRiskConfig) ProtoMessage() {}

func (x *Req_RecommendRiskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_RecommendRiskConfig.ProtoReflect.Descriptor instead.
func (*Req_RecommendRiskConfig) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{10}
}

func (x *Req_RecommendRiskConfig) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Req_RecommendRiskConfig) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Req_RecommendRiskConfig) GetOperatorToken() string {
	if x != nil {
		return x.OperatorToken
	}
	return ""
}

func (x *Req_RecommendRiskConfig) GetUsingRTP() int32 {
	if x != nil {
		return x.UsingRTP
	}
	return 0
}

type Res_RecommendRiskConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Threshold   float64 `protobuf:"fixed64,1,opt,name=Threshold,proto3" json:"Threshold,omitempty"`
	ReSpinTimes int32   `protobuf:"varint,2,opt,name=ReSpinTimes,proto3" json:"ReSpinTimes,omitempty"`
}

func (x *Res_RecommendRiskConfig) Reset() {
	*x = Res_RecommendRiskConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_RecommendRiskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_RecommendRiskConfig) ProtoMessage() {}

func (x *Res_RecommendRiskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_RecommendRiskConfig.ProtoReflect.Descriptor instead.
func (*Res_RecommendRiskConfig) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{11}
}

func (x *Res_RecommendRiskConfig) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Res_RecommendRiskConfig) GetReSpinTimes() int32 {
	if x != nil {
		return x.ReSpinTimes
	}
	return 0
}

type Req_AddLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *Req_AddLogin) Reset() {
	*x = Req_AddLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_AddLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_AddLogin) ProtoMessage() {}

func (x *Req_AddLogin) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_AddLogin.ProtoReflect.Descriptor instead.
func (*Req_AddLogin) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{12}
}

func (x *Req_AddLogin) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type Res_AddLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Res_AddLogin) Reset() {
	*x = Res_AddLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_AddLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_AddLogin) ProtoMessage() {}

func (x *Res_AddLogin) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_AddLogin.ProtoReflect.Descriptor instead.
func (*Res_AddLogin) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{13}
}

type Req_UpdateOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId        int32   `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	RoleId        string  `protobuf:"bytes,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	OperatorToken string  `protobuf:"bytes,3,opt,name=OperatorToken,proto3" json:"OperatorToken,omitempty"`
	ParentId      int64   `protobuf:"varint,4,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	SubId         int64   `protobuf:"varint,5,opt,name=SubId,proto3" json:"SubId,omitempty"`
	Bet           float64 `protobuf:"fixed64,6,opt,name=Bet,proto3" json:"Bet,omitempty"`
	Score         float64 `protobuf:"fixed64,7,opt,name=Score,proto3" json:"Score,omitempty"`
	Status        int64   `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	CurrencyCode  string  `protobuf:"bytes,9,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	CurrencyMult  int64   `protobuf:"varint,10,opt,name=CurrencyMult,proto3" json:"CurrencyMult,omitempty"`
	MathVersion   string  `protobuf:"bytes,11,opt,name=MathVersion,proto3" json:"MathVersion,omitempty"`
	ExchangeRate  float64 `protobuf:"fixed64,12,opt,name=ExchangeRate,proto3" json:"ExchangeRate,omitempty"`
	IsNewPlayer   bool    `protobuf:"varint,13,opt,name=IsNewPlayer,proto3" json:"IsNewPlayer,omitempty"`
	IsActivity    bool    `protobuf:"varint,14,opt,name=IsActivity,proto3" json:"IsActivity,omitempty"`
	RoundEnd      bool    `protobuf:"varint,15,opt,name=RoundEnd,proto3" json:"RoundEnd,omitempty"`
	UseTag        bool    `protobuf:"varint,16,opt,name=UseTag,proto3" json:"UseTag,omitempty"`
}

func (x *Req_UpdateOrder) Reset() {
	*x = Req_UpdateOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_UpdateOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_UpdateOrder) ProtoMessage() {}

func (x *Req_UpdateOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_UpdateOrder.ProtoReflect.Descriptor instead.
func (*Req_UpdateOrder) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{14}
}

func (x *Req_UpdateOrder) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Req_UpdateOrder) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Req_UpdateOrder) GetOperatorToken() string {
	if x != nil {
		return x.OperatorToken
	}
	return ""
}

func (x *Req_UpdateOrder) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Req_UpdateOrder) GetSubId() int64 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *Req_UpdateOrder) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *Req_UpdateOrder) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Req_UpdateOrder) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Req_UpdateOrder) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Req_UpdateOrder) GetCurrencyMult() int64 {
	if x != nil {
		return x.CurrencyMult
	}
	return 0
}

func (x *Req_UpdateOrder) GetMathVersion() string {
	if x != nil {
		return x.MathVersion
	}
	return ""
}

func (x *Req_UpdateOrder) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *Req_UpdateOrder) GetIsNewPlayer() bool {
	if x != nil {
		return x.IsNewPlayer
	}
	return false
}

func (x *Req_UpdateOrder) GetIsActivity() bool {
	if x != nil {
		return x.IsActivity
	}
	return false
}

func (x *Req_UpdateOrder) GetRoundEnd() bool {
	if x != nil {
		return x.RoundEnd
	}
	return false
}

func (x *Req_UpdateOrder) GetUseTag() bool {
	if x != nil {
		return x.UseTag
	}
	return false
}

type Res_UpdateOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Res_UpdateOrder) Reset() {
	*x = Res_UpdateOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_UpdateOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_UpdateOrder) ProtoMessage() {}

func (x *Res_UpdateOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_UpdateOrder.ProtoReflect.Descriptor instead.
func (*Res_UpdateOrder) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{15}
}

type Req_GetUserTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *Req_GetUserTag) Reset() {
	*x = Req_GetUserTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_GetUserTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_GetUserTag) ProtoMessage() {}

func (x *Req_GetUserTag) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_GetUserTag.ProtoReflect.Descriptor instead.
func (*Req_GetUserTag) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{16}
}

func (x *Req_GetUserTag) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type Res_GetUserTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasTag            bool    `protobuf:"varint,1,opt,name=HasTag,proto3" json:"HasTag,omitempty"`
	HitProbability120 float64 `protobuf:"fixed64,2,opt,name=HitProbability120,proto3" json:"HitProbability120,omitempty"`
	HitProbability150 float64 `protobuf:"fixed64,3,opt,name=HitProbability150,proto3" json:"HitProbability150,omitempty"`
}

func (x *Res_GetUserTag) Reset() {
	*x = Res_GetUserTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_GetUserTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_GetUserTag) ProtoMessage() {}

func (x *Res_GetUserTag) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_GetUserTag.ProtoReflect.Descriptor instead.
func (*Res_GetUserTag) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{17}
}

func (x *Res_GetUserTag) GetHasTag() bool {
	if x != nil {
		return x.HasTag
	}
	return false
}

func (x *Res_GetUserTag) GetHitProbability120() float64 {
	if x != nil {
		return x.HitProbability120
	}
	return 0
}

func (x *Res_GetUserTag) GetHitProbability150() float64 {
	if x != nil {
		return x.HitProbability150
	}
	return 0
}

type Req_GetUserBreakProtect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId      string  `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	Balance     float64 `protobuf:"fixed64,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
	MinBetLevel float64 `protobuf:"fixed64,3,opt,name=MinBetLevel,proto3" json:"MinBetLevel,omitempty"`
}

func (x *Req_GetUserBreakProtect) Reset() {
	*x = Req_GetUserBreakProtect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_GetUserBreakProtect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_GetUserBreakProtect) ProtoMessage() {}

func (x *Req_GetUserBreakProtect) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_GetUserBreakProtect.ProtoReflect.Descriptor instead.
func (*Req_GetUserBreakProtect) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{18}
}

func (x *Req_GetUserBreakProtect) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Req_GetUserBreakProtect) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Req_GetUserBreakProtect) GetMinBetLevel() float64 {
	if x != nil {
		return x.MinBetLevel
	}
	return 0
}

type Res_GetUserBreakProtect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BreakProtect   bool    `protobuf:"varint,1,opt,name=BreakProtect,proto3" json:"BreakProtect,omitempty"`
	HitProbability float64 `protobuf:"fixed64,2,opt,name=HitProbability,proto3" json:"HitProbability,omitempty"`
	NotHitRTP      int32   `protobuf:"varint,3,opt,name=NotHitRTP,proto3" json:"NotHitRTP,omitempty"`
	HitRTP         int32   `protobuf:"varint,4,opt,name=HitRTP,proto3" json:"HitRTP,omitempty"`
}

func (x *Res_GetUserBreakProtect) Reset() {
	*x = Res_GetUserBreakProtect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_GetUserBreakProtect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_GetUserBreakProtect) ProtoMessage() {}

func (x *Res_GetUserBreakProtect) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_GetUserBreakProtect.ProtoReflect.Descriptor instead.
func (*Res_GetUserBreakProtect) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{19}
}

func (x *Res_GetUserBreakProtect) GetBreakProtect() bool {
	if x != nil {
		return x.BreakProtect
	}
	return false
}

func (x *Res_GetUserBreakProtect) GetHitProbability() float64 {
	if x != nil {
		return x.HitProbability
	}
	return 0
}

func (x *Res_GetUserBreakProtect) GetNotHitRTP() int32 {
	if x != nil {
		return x.NotHitRTP
	}
	return 0
}

func (x *Res_GetUserBreakProtect) GetHitRTP() int32 {
	if x != nil {
		return x.HitRTP
	}
	return 0
}

type Req_UseBreakProtect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
}

func (x *Req_UseBreakProtect) Reset() {
	*x = Req_UseBreakProtect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req_UseBreakProtect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req_UseBreakProtect) ProtoMessage() {}

func (x *Req_UseBreakProtect) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req_UseBreakProtect.ProtoReflect.Descriptor instead.
func (*Req_UseBreakProtect) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{20}
}

func (x *Req_UseBreakProtect) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type Res_UseBreakProtect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Res_UseBreakProtect) Reset() {
	*x = Res_UseBreakProtect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_UseBreakProtect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_UseBreakProtect) ProtoMessage() {}

func (x *Res_UseBreakProtect) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_UseBreakProtect.ProtoReflect.Descriptor instead.
func (*Res_UseBreakProtect) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{21}
}

var File_order_srv_proto protoreflect.FileDescriptor

var file_order_srv_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x50, 0x61, 0x67, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x22, 0xd6, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x5f, 0x47, 0x65, 0x74, 0x48, 0x69,
	0x73, 0x6f, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x52, 0x6f, 0x77, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x67, 0x65, 0x52, 0x6f, 0x77, 0x22, 0x34, 0x0a, 0x0e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2b, 0x0a, 0x0b, 0x52, 0x65,
	0x71, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x75,
	0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x27, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x5f, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f,
	0x22, 0xc2, 0x02, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x75, 0x62,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x53, 0x75, 0x72, 0x70, 0x6c, 0x75, 0x73, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x53, 0x75, 0x72, 0x70, 0x6c, 0x75, 0x73, 0x43, 0x6f, 0x69,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x42, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x42, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x42, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x7f, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x5f, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2e, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x50, 0x61, 0x67,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x08, 0x43, 0x6f,
	0x6d, 0x50, 0x61, 0x67, 0x65, 0x72, 0x22, 0x68, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x5f, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x74, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x24, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x5f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x52, 0x74, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x54, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x52, 0x54, 0x50, 0x22, 0x8b, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x5f, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x69, 0x6e,
	0x67, 0x52, 0x54, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x55, 0x73, 0x69, 0x6e,
	0x67, 0x52, 0x54, 0x50, 0x22, 0x59, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x5f, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x52, 0x65, 0x53, 0x70, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x52, 0x65, 0x53, 0x70, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22,
	0x26, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x5f, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x5f, 0x41,
	0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0xdd, 0x03, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x5f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x75,
	0x62, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x42, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x4d, 0x75, 0x6c, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4d,
	0x61, 0x74, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x4d, 0x61, 0x74, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x0c, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0c, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x6e, 0x64, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x6e, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x54, 0x61, 0x67, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x54, 0x61, 0x67, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x5f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x5f, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x73, 0x54, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x48, 0x61, 0x73, 0x54, 0x61, 0x67, 0x12,
	0x2c, 0x0a, 0x11, 0x48, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x31, 0x32, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x48, 0x69, 0x74, 0x50,
	0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x31, 0x32, 0x30, 0x12, 0x2c, 0x0a,
	0x11, 0x48, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x31,
	0x35, 0x30, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x48, 0x69, 0x74, 0x50, 0x72, 0x6f,
	0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x31, 0x35, 0x30, 0x22, 0x6d, 0x0a, 0x17, 0x52,
	0x65, 0x71, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50,
	0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x69, 0x6e, 0x42,
	0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x4d,
	0x69, 0x6e, 0x42, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x9b, 0x01, 0x0a, 0x17, 0x52,
	0x65, 0x73, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50,
	0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50,
	0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x42, 0x72,
	0x65, 0x61, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x48, 0x69,
	0x74, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0e, 0x48, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x48, 0x69, 0x74, 0x52, 0x54, 0x50, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4e, 0x6f, 0x74, 0x48, 0x69, 0x74, 0x52, 0x54, 0x50,
	0x12, 0x16, 0x0a, 0x06, 0x48, 0x69, 0x74, 0x52, 0x54, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x48, 0x69, 0x74, 0x52, 0x54, 0x50, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x5f,
	0x55, 0x73, 0x65, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x5f, 0x55,
	0x73, 0x65, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x32, 0xb9,
	0x06, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x72, 0x76, 0x12, 0x43, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x6f,
	0x74, 0x72, 0x79, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x5f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x1a, 0x15, 0x2e, 0x70, 0x62,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x6f, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x1a, 0x15, 0x2e,
	0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x52, 0x74, 0x70, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52,
	0x74, 0x70, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x5f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x74, 0x70, 0x22, 0x00,
	0x12, 0x5d, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x69, 0x73,
	0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x52, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x21, 0x2e, 0x70, 0x62, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x52, 0x69, 0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x00, 0x12,
	0x3c, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x70, 0x62,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x41, 0x64, 0x64, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x5f, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70,
	0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x1a, 0x18, 0x2e, 0x70,
	0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x12,
	0x21, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65,
	0x63, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x5f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x50, 0x72,
	0x6f, 0x74, 0x65, 0x63, 0x74, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x42, 0x72,
	0x65, 0x61, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x5f, 0x55, 0x73, 0x65, 0x42, 0x72, 0x65,
	0x61, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x55, 0x73, 0x65, 0x42, 0x72, 0x65, 0x61,
	0x6b, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x70, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_srv_proto_rawDescOnce sync.Once
	file_order_srv_proto_rawDescData = file_order_srv_proto_rawDesc
)

func file_order_srv_proto_rawDescGZIP() []byte {
	file_order_srv_proto_rawDescOnce.Do(func() {
		file_order_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_srv_proto_rawDescData)
	})
	return file_order_srv_proto_rawDescData
}

var file_order_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_order_srv_proto_goTypes = []interface{}{
	(*ComPager)(nil),                // 0: pb_order.ComPager
	(*Req_GetHisotry)(nil),          // 1: pb_order.Req_GetHisotry
	(*GenerateResult)(nil),          // 2: pb_order.GenerateResult
	(*Empty)(nil),                   // 3: pb_order.Empty
	(*Req_OrderNo)(nil),             // 4: pb_order.Req_OrderNo
	(*Res_OrderNo)(nil),             // 5: pb_order.Res_OrderNo
	(*OrderHistoryItem)(nil),        // 6: pb_order.OrderHistoryItem
	(*Res_HistoryList)(nil),         // 7: pb_order.Res_HistoryList
	(*Req_RecommendRtp)(nil),        // 8: pb_order.Req_RecommendRtp
	(*Res_RecommendRtp)(nil),        // 9: pb_order.Res_RecommendRtp
	(*Req_RecommendRiskConfig)(nil), // 10: pb_order.Req_RecommendRiskConfig
	(*Res_RecommendRiskConfig)(nil), // 11: pb_order.Res_RecommendRiskConfig
	(*Req_AddLogin)(nil),            // 12: pb_order.Req_AddLogin
	(*Res_AddLogin)(nil),            // 13: pb_order.Res_AddLogin
	(*Req_UpdateOrder)(nil),         // 14: pb_order.Req_UpdateOrder
	(*Res_UpdateOrder)(nil),         // 15: pb_order.Res_UpdateOrder
	(*Req_GetUserTag)(nil),          // 16: pb_order.Req_GetUserTag
	(*Res_GetUserTag)(nil),          // 17: pb_order.Res_GetUserTag
	(*Req_GetUserBreakProtect)(nil), // 18: pb_order.Req_GetUserBreakProtect
	(*Res_GetUserBreakProtect)(nil), // 19: pb_order.Res_GetUserBreakProtect
	(*Req_UseBreakProtect)(nil),     // 20: pb_order.Req_UseBreakProtect
	(*Res_UseBreakProtect)(nil),     // 21: pb_order.Res_UseBreakProtect
	(*anypb.Any)(nil),               // 22: google.protobuf.Any
}
var file_order_srv_proto_depIdxs = []int32{
	22, // 0: pb_order.OrderHistoryItem.Role:type_name -> google.protobuf.Any
	6,  // 1: pb_order.Res_HistoryList.HistoryItem:type_name -> pb_order.OrderHistoryItem
	0,  // 2: pb_order.Res_HistoryList.ComPager:type_name -> pb_order.ComPager
	1,  // 3: pb_order.OrderSrv.GetHistory:input_type -> pb_order.Req_GetHisotry
	3,  // 4: pb_order.OrderSrv.GenerationOrderNo:input_type -> pb_order.Empty
	4,  // 5: pb_order.OrderSrv.ProduceOrderNo:input_type -> pb_order.Req_OrderNo
	4,  // 6: pb_order.OrderSrv.ConsumeOrderNo:input_type -> pb_order.Req_OrderNo
	8,  // 7: pb_order.OrderSrv.RecommendRtp:input_type -> pb_order.Req_RecommendRtp
	10, // 8: pb_order.OrderSrv.RecommendRiskConfig:input_type -> pb_order.Req_RecommendRiskConfig
	12, // 9: pb_order.OrderSrv.AddLogin:input_type -> pb_order.Req_AddLogin
	14, // 10: pb_order.OrderSrv.UpdateOrder:input_type -> pb_order.Req_UpdateOrder
	16, // 11: pb_order.OrderSrv.GetUserTag:input_type -> pb_order.Req_GetUserTag
	18, // 12: pb_order.OrderSrv.GetUserBreakProtect:input_type -> pb_order.Req_GetUserBreakProtect
	20, // 13: pb_order.OrderSrv.UseBreakProtect:input_type -> pb_order.Req_UseBreakProtect
	7,  // 14: pb_order.OrderSrv.GetHistory:output_type -> pb_order.Res_HistoryList
	2,  // 15: pb_order.OrderSrv.GenerationOrderNo:output_type -> pb_order.GenerateResult
	5,  // 16: pb_order.OrderSrv.ProduceOrderNo:output_type -> pb_order.Res_OrderNo
	5,  // 17: pb_order.OrderSrv.ConsumeOrderNo:output_type -> pb_order.Res_OrderNo
	9,  // 18: pb_order.OrderSrv.RecommendRtp:output_type -> pb_order.Res_RecommendRtp
	11, // 19: pb_order.OrderSrv.RecommendRiskConfig:output_type -> pb_order.Res_RecommendRiskConfig
	13, // 20: pb_order.OrderSrv.AddLogin:output_type -> pb_order.Res_AddLogin
	15, // 21: pb_order.OrderSrv.UpdateOrder:output_type -> pb_order.Res_UpdateOrder
	17, // 22: pb_order.OrderSrv.GetUserTag:output_type -> pb_order.Res_GetUserTag
	19, // 23: pb_order.OrderSrv.GetUserBreakProtect:output_type -> pb_order.Res_GetUserBreakProtect
	21, // 24: pb_order.OrderSrv.UseBreakProtect:output_type -> pb_order.Res_UseBreakProtect
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_order_srv_proto_init() }
func file_order_srv_proto_init() {
	if File_order_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComPager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_GetHisotry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_OrderNo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_OrderNo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderHistoryItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_HistoryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_RecommendRtp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_RecommendRtp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_RecommendRiskConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_RecommendRiskConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_AddLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_AddLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_UpdateOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_UpdateOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_GetUserTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_GetUserTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_GetUserBreakProtect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_GetUserBreakProtect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req_UseBreakProtect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_UseBreakProtect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_srv_proto_goTypes,
		DependencyIndexes: file_order_srv_proto_depIdxs,
		MessageInfos:      file_order_srv_proto_msgTypes,
	}.Build()
	File_order_srv_proto = out.File
	file_order_srv_proto_rawDesc = nil
	file_order_srv_proto_goTypes = nil
	file_order_srv_proto_depIdxs = nil
}
